### ISSUE TITLE
Penangf organization

### ISSUE THREAD

**Issue by progzone122** [moto-penangf/documentation#4]
How about moving all our resources into a separate organization for quick access and so we can both edit without giving out permissions every time.

I've already sent you an invitation. I've also granted you Owner rights

**Comment by progzone122** [comment]
@shomykohai

**Comment by shomykohai** [comment]
Seems fair!

**Comment by progzone122** [comment]
After the move, we'll need to fix all the links

**Comment by shomykohai** [comment]
Moved the documentation!

**Comment by progzone122** [comment]
I've moved all the other resources. We need to fix the links

**Comment by progzone122** [comment]
You'll also need to reconfigure GitHub Pages

**Comment by progzone122** [comment]
I also suggest renaming the repository to "website" / "tutorials" or something else.
So it would be “moto-penangf/website” / “moto-penangf/totorials”

**Comment by shomykohai** [comment]
GitHub pages is already live: https://moto-penangf.github.io/documentation/#/

I tried updating the links but git complains about permissions and stuff, probably it still has the reference to the repo as mine and not as an org one

**Comment by progzone122** [comment]
> GitHub pages is already live: https://moto-penangf.github.io/documentation/#/
> 
> I tried updating the links but git complains about permissions and stuff, probably it still has the reference to the repo as mine and not as an org one

Looks like we don't need to edit the links, it redirects correctly

**Comment by progzone122** [comment]
The move's over
